import dedent from "dedent";
import { createChecklist, parseChecklists } from "../../lib/models/checklist";

describe("createChecklist", () => {
  it("creates a checklist", () => {
    const checklist = createChecklist("auto", "semver", [
      {
        id: "major",
        checked: false,
        body: "major",
      },
      {
        id: "minor",
        checked: true,
        body: "minor",
      },
    ]);
    expect(checklist).toBe(dedent`
      - [ ] <!-- auto:semver:f1425da40a9f2d21ab702a1c7feae026 --> major
      - [x] <!-- auto:semver:ab846c0e3717a3e7d14af45cab70b44a --> minor 
    `);
  });
});

describe("parseChecklists", () => {
  it("returns a checklist from a text string", () => {
    const testString = dedent`
    blah blah
    - [ ] <!-- auto:semver:f1425da40a9f2d21ab702a1c7feae026 --> Does a major release
    blah
    `;

    expect(parseChecklists(testString)).toEqual({
      auto: {
        semver: {
          id: "semver",
          namespace: "auto",
          items: [
            {
              id: "f1425da40a9f2d21ab702a1c7feae026",
              checked: false,
              body: "Does a major release",
            },
          ],
        },
      },
    });
  });

  it("combines checks into a single checklist", () => {
    const testString = dedent`
    - [ ] <!-- auto:semver:major --> abc
    - [ ] <!-- auto:semver:minor --> abc
    - [x] <!-- auto:changelog:docs --> abc
    `;

    expect(parseChecklists(testString)).toEqual({
      auto: {
        semver: {
          id: "semver",
          namespace: "auto",
          items: [
            {
              id: "major",
              checked: false,
              body: "abc",
            },
            {
              id: "minor",
              checked: false,
              body: "abc",
            },
          ],
        },
        changelog: {
          id: "changelog",
          namespace: "auto",
          items: [
            {
              id: "docs",
              checked: true,
              body: "abc",
            },
          ],
        },
      },
    });
  });

  it("parses a full checklist", () => {
    const testString = dedent`
      <img align="left" width="60" src="https://autobot.auto-it.now.sh/public/logo.png"/>

      ### Choose a release label

      This repository uses [auto](https://github.com/intuit/auto) to generate releases. In order to do that, 
      it needs an appropriate label assigned to each PR. Choose a label below that you feel best suites your changes.

      ##

      <sub>_**Semver Labels** (choose one at most)_</sub>

      - [x] <!-- auto:semver:major --> <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=bfd4f2&text=Version: Major"/> 
      - [ ] <!-- auto:semver:minor --> <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=60e519&text=Version: Minor"/> 
      - [ ] <!-- auto:semver:patch --> <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=79B2F2&text=Version: Patch"/>

      ##

      <sub>_**Skip Release Labels**_</sub>

      - [ ] <!-- auto:skiprelease:skip_release --> <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=D4F279&text=skip-release"/> 
      - [ ] <!-- auto:skiprelease:versiontrivial --> <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=413693&text=Version: Trivial"/> 
      - [ ] <!-- auto:skiprelease:skiprelease --> <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=d4c5f9&text=Skip Release"/> 
      - [ ] <!-- auto:skiprelease:docs --> <img align="center" src="https://autobot.auto-it.now.sh/l/label?color=EC79F2&text=Docs"/>

      <sub>_Generated by [auto-it](https://github.com/apps/auto-it)_</sub>
    `;

    expect(parseChecklists(testString, "auto")).toMatchInlineSnapshot(`
      Object {
        "semver": Object {
          "id": "semver",
          "items": Array [
            Object {
              "body": "<img align=\\"center\\" src=\\"https://autobot.auto-it.now.sh/l/label?color=bfd4f2&text=Version: Major\\"/> ",
              "checked": true,
              "id": "major",
            },
            Object {
              "body": "<img align=\\"center\\" src=\\"https://autobot.auto-it.now.sh/l/label?color=60e519&text=Version: Minor\\"/> ",
              "checked": false,
              "id": "minor",
            },
            Object {
              "body": "<img align=\\"center\\" src=\\"https://autobot.auto-it.now.sh/l/label?color=79B2F2&text=Version: Patch\\"/>",
              "checked": false,
              "id": "patch",
            },
          ],
          "namespace": "auto",
        },
        "skiprelease": Object {
          "id": "skiprelease",
          "items": Array [
            Object {
              "body": "<img align=\\"center\\" src=\\"https://autobot.auto-it.now.sh/l/label?color=D4F279&text=skip-release\\"/> ",
              "checked": false,
              "id": "skip_release",
            },
            Object {
              "body": "<img align=\\"center\\" src=\\"https://autobot.auto-it.now.sh/l/label?color=413693&text=Version: Trivial\\"/> ",
              "checked": false,
              "id": "versiontrivial",
            },
            Object {
              "body": "<img align=\\"center\\" src=\\"https://autobot.auto-it.now.sh/l/label?color=d4c5f9&text=Skip Release\\"/> ",
              "checked": false,
              "id": "skiprelease",
            },
            Object {
              "body": "<img align=\\"center\\" src=\\"https://autobot.auto-it.now.sh/l/label?color=EC79F2&text=Docs\\"/>",
              "checked": false,
              "id": "docs",
            },
          ],
          "namespace": "auto",
        },
      }
    `);
  });
});
