version: 2.1

orbs:
  yarn: artsy/yarn@2.0.0

jobs:
  deploy-production:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Deploy to production
          command: |
            npx now --scope=auto-it --token=${NOW_TOKEN} -e APP_ID -e NODE_ENV=production -e PRIVATE_KEY -e SENTRY_DSN -e WEBHOOK_SECRET
  deploy-development:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Deploy to development
          command: |
            npx now --scope=auto-it --token=${NOW_TOKEN} -e NODE_ENV=development

workflows:
  build_and_verify:
    jobs:
      - yarn/update-cache
      - yarn/lint
      - yarn/type-check
      - yarn/jest
      - deploy-development:
          context: autobot-development
          filters:
            branches:
              ignore:
                - master
          requires:
            - yarn/update-cache
            - yarn/lint
            - yarn/type-check
            - yarn/jest
      - deploy-production:
          context: autobot-production
          filters:
            branches:
              only: master
          requires:
            - yarn/update-cache
            - yarn/lint
            - yarn/type-check
            - yarn/jest
