import { PRContext } from "../models/context";
import { LabelRelease, LabelError } from "../models/release";
import { Config, getConfig } from "../models/config";
import dedent from "dedent";
import { createChecklist } from "../models/checklist";
import { renderLabel, populateLabel, getSkipReleaseLabelsFromConfig } from "../models/label";
import { sub, italics, bold } from "../utils/markdown";
import { WebhookPayloadPullRequest } from "@octokit/webhooks";
import { Context } from "probot";
import { getLabelRelease } from "../models/release";

const createAutoChecklist = createChecklist.bind(null, "auto");

const MessageStart = "<!--- AutoPR:START --->";
const MessageEnd = "<!--- AutoPR:END --->";

const onBoardingMessage = (sections: string[]) => dedent`
    <!-- DO NOT EDIT -->
    ${MessageStart} 
    ---

    <img align="left" width="60" src="https://autobot.auto-it.now.sh/public/logo.png"/>

    ### Choose a release label

    This repository uses [auto](https://github.com/intuit/auto) to generate releases. In order to do that, 
    it needs an appropriate label assigned to each PR. Choose a label below that you feel best suites your changes.

    ${sections.join("\n\n")}
    
    <sub>_Generated by [auto-it](https://github.com/apps/auto-it)_</sub>
    ${MessageEnd} 
  `;

const sectionHeader = (text: string, secondaryText?: string, info?: string) =>
  sub(italics(`${bold(text)}${secondaryText ? ` ${secondaryText}` : ""}`));

const section = (header: string, checklist: string) => dedent`
    ##

    ${header}
    
    ${checklist}
    `;

const createLabelChecklists = async (context: PRContext, config: Config) => {
  // Fetch labels from config
  const { owner, repo } = context.repo();
  const { data: labels } = await context.github.issues.listLabelsForRepo({ owner, repo });
  // See which labels are in the repo, create the ones that don't exist

  const semverHead = sectionHeader("Semver Labels", "(choose one at most)");
  const semverChecklist = createAutoChecklist(
    "semver",
    await Promise.all(
      ["major", "minor", "patch"].map(async labelType => {
        const label = await populateLabel(labelType, config.labels[labelType], context, labels);

        return {
          id: labelType,
          checked: false,
          body: renderLabel(label),
        };
      }),
    ),
  );

  const skipReleaseHead = sectionHeader("Skip Release Labels");
  const skipReleaseChecklist = createAutoChecklist(
    "skiprelease",
    await Promise.all(
      getSkipReleaseLabelsFromConfig(config).map(async labelConfig => {
        const label = await populateLabel("skip-release", labelConfig, context, labels);

        return {
          id: label.name,
          checked: false,
          body: renderLabel(label),
        };
      }),
    ),
  );

  return [section(semverHead, semverChecklist), section(skipReleaseHead, skipReleaseChecklist)];
};

const hasLabels = (release: LabelRelease) =>
  release.kind === "invalid" && release.reason === LabelError.NoLabels ? false : true;

export default async (context: Context<WebhookPayloadPullRequest>) => {
  const config = await getConfig(context);
  const release = getLabelRelease(context, config);

  if (context.payload.action === "opened" && hasLabels(release) === false) {
    const { owner, repo, number: issue_number } = context.issue();
    // Initial on-boarding
    context.github.issues.update({
      owner,
      repo,
      issue_number,
      body:
        context.payload.pull_request.body + "\n\n" + onBoardingMessage(await createLabelChecklists(context, config)),
    });
  }
};
